[package]
name = "santa-lang"
version = "0.0.1"
edition = "2021"

[dependencies]
im-rc = { git = "https://github.com/eddmann/im-rs.git", features = ["pool"] }
ordered-float = "3.6.0"
regex = "1.7.3"

[dev-dependencies]
expect-test = "1.0"
