name: Build Lambda

on:
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set release version
        run: |
          sed -i 's/version = "[0-9.]*"$/version = "${{ inputs.release-tag }}"/' Cargo.toml
      - name: Build
        run: make lambda/build
      - name: Upload
        run: |
          cp target/lambda/release/santa-lambda.zip santa-lang-lambda-${{ inputs.release-tag }}.zip
          gh release upload ${{ inputs.release-tag }} santa-lang-lambda-${{ inputs.release-tag }}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
