name: Build Web

on:
  push:
    branches:
      - main

concurrency: build-web

jobs:
  package:
    name: Package
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          target: wasm32-unknown-unknown
          override: true
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: v0.11.0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Build
        run: RUST_LOG=info wasm-pack build web/library
      - name: Pack
        working-directory: web/library/pkg
        run: |
          npm pkg set 'name'='@eddmann/santa-lang-wasm'
          npm pkg set 'version'='0.0.1'
          npm pkg set 'repository'='https://github.com/eddmann/santa-lang-rs'
          npm pkg set 'publishConfig.registry'='https://npm.pkg.github.com'
          wasm-pack pack
      - name: Publish
        working-directory: web/library/pkg
        run: |
          echo @eddmann:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          target: wasm32-unknown-unknown
          override: true
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: v0.11.0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Build WebAssembly
        run: RUST_LOG=info wasm-pack build web/library
      - name: Build Client
        run: cd web/client && yarn && yarn build
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: web/client/out
