name: Build WebAssembly

on:
  workflow_call:

concurrency: build-wasm

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          target: wasm32-unknown-unknown
          override: true
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: v0.11.0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Build
        run: RUST_LOG=info wasm-pack build wasm --release
      - name: Pack
        working-directory: wasm/pkg
        run: |
          npm pkg set 'name'='@eddmann/santa-lang-wasm'
          npm pkg set 'repository'='https://github.com/eddmann/santa-lang-rs'
          wasm-pack pack
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: santa-lang-wasm.tgz
          path: wasm/pkg/eddmann-santa-lang-wasm-*.tgz
          retention-days: 5
