name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Restore Cargo cache
        uses: actions/cache@v3
        with:
          path: ./.cargo
          key: test-cargo-${{ hashFiles('./Cargo.lock') }}
          restore-keys: test-cargo-
      - name: Test
        run: make can-release
