name: Test

on:
  push:
    branches-ignore:
      - draft-release

jobs:
  test-lang:
    name: Test Lang
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load cache
        uses: actions/cache@v4
        with:
          path: ./.cargo
          key: test-lang-cargo-${{ hashFiles('./Cargo.lock') }}
          restore-keys: test-lang-cargo-
      - name: Test
        run: make test/lang

  test-cli:
    name: Test CLI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load cache
        uses: actions/cache@v4
        with:
          path: ./.cargo
          key: test-cli-cargo-${{ hashFiles('./Cargo.lock') }}
          restore-keys: test-cli-cargo-
      - name: Test
        run: make test/cli

  test-wasm:
    name: Test WebAssembly
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0
          targets: wasm32-unknown-unknown
      - name: Load Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Test
        run: make test/wasm

  update-draft-release-branch:
    needs:
      - test-lang
      - test-cli
      - test-wasm
    if: github.ref == 'refs/heads/main'
    name: Update draft release branch
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Update
        uses: alice-biometrics/github-push-action@v0.7.0
        with:
          branch: draft-release
          force: true
          github_token: ${{ secrets.RELEASE_TOKEN }}
